/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    EducationConcept: typeof import('./src/components/EducationConcept.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    FooterSection: typeof import('./src/components/FooterSection.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    HeroSection: typeof import('./src/components/HeroSection.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTick: typeof import('./src/components/icons/IconTick.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    LatestCourses: typeof import('./src/components/LatestCourses.vue')['default']
    LazyImage: typeof import('./src/components/LazyImage.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    PopWechatButton: typeof import('./src/components/PopWechatButton.vue')['default']
    PrintInfo: typeof import('./src/components/PrintInfo.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SchoolProfile: typeof import('./src/components/SchoolProfile.vue')['default']
    ShowMsg: typeof import('./src/components/ShowMsg.vue')['default']
    SideButton: typeof import('./src/components/SideButton.vue')['default']
    SkeletonScreen: typeof import('./src/components/SkeletonScreen.vue')['default']
    TeacherTeam: typeof import('./src/components/TeacherTeam.vue')['default']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
